//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYZ_University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCours
    {
        public tblCours()
        {
            this.tblStudents = new HashSet<tblStudent>();
        }
    
        public int CourseId { get; set; }
        public int FacultyId { get; set; }
        public string CourseName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int Creator_UserId { get; set; }
    
        public virtual tblFaculty tblFaculty { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblStudent> tblStudents { get; set; }
    }
}
