//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYZ_University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public tblStudent()
        {
            this.tblTuitionFeePayments = new HashSet<tblTuitionFeePayment>();
        }
    
        public int StudentId { get; set; }
        public int CourseId { get; set; }
        public string RegistrationNo { get; set; }
        public string FullName { get; set; }
        public int NationalId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int Creator_UserId { get; set; }
        public Nullable<decimal> FeeBalance { get; set; }
    
        public virtual tblCours tblCours { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblTuitionFeePayment> tblTuitionFeePayments { get; set; }
    }
}
