//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYZ_University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTuitionFee
    {
        public int TuitionFeeId { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DueDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int Creator_UserId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
