//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYZ_University
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblCourses = new HashSet<tblCours>();
            this.tblFaculties = new HashSet<tblFaculty>();
            this.tblStudents = new HashSet<tblStudent>();
            this.tblTuitionFees = new HashSet<tblTuitionFee>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ICollection<tblCours> tblCourses { get; set; }
        public virtual ICollection<tblFaculty> tblFaculties { get; set; }
        public virtual ICollection<tblStudent> tblStudents { get; set; }
        public virtual ICollection<tblTuitionFee> tblTuitionFees { get; set; }
    }
}
