//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XYZ_University
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class XYZ_UniversityEntities : DbContext
    {
        public XYZ_UniversityEntities()
            : base("name=XYZ_UniversityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCours> tblCourses { get; set; }
        public DbSet<tblFaculty> tblFaculties { get; set; }
        public DbSet<tblStudent> tblStudents { get; set; }
        public DbSet<tblTuitionFeePayment> tblTuitionFeePayments { get; set; }
        public DbSet<tblTuitionFee> tblTuitionFees { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
    
        public virtual ObjectResult<proc_addTuitionFeePayment_Result> proc_addTuitionFeePayment(string registrationNo, string transactionNo, Nullable<System.DateTime> paymentDate, Nullable<decimal> paymentAmount, string paymentMethod, string paidBy, string remarks)
        {
            var registrationNoParameter = registrationNo != null ?
                new ObjectParameter("RegistrationNo", registrationNo) :
                new ObjectParameter("RegistrationNo", typeof(string));
    
            var transactionNoParameter = transactionNo != null ?
                new ObjectParameter("TransactionNo", transactionNo) :
                new ObjectParameter("TransactionNo", typeof(string));
    
            var paymentDateParameter = paymentDate.HasValue ?
                new ObjectParameter("PaymentDate", paymentDate) :
                new ObjectParameter("PaymentDate", typeof(System.DateTime));
    
            var paymentAmountParameter = paymentAmount.HasValue ?
                new ObjectParameter("PaymentAmount", paymentAmount) :
                new ObjectParameter("PaymentAmount", typeof(decimal));
    
            var paymentMethodParameter = paymentMethod != null ?
                new ObjectParameter("PaymentMethod", paymentMethod) :
                new ObjectParameter("PaymentMethod", typeof(string));
    
            var paidByParameter = paidBy != null ?
                new ObjectParameter("PaidBy", paidBy) :
                new ObjectParameter("PaidBy", typeof(string));
    
            var remarksParameter = remarks != null ?
                new ObjectParameter("Remarks", remarks) :
                new ObjectParameter("Remarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_addTuitionFeePayment_Result>("proc_addTuitionFeePayment", registrationNoParameter, transactionNoParameter, paymentDateParameter, paymentAmountParameter, paymentMethodParameter, paidByParameter, remarksParameter);
        }
    
        public virtual ObjectResult<proc_verifyAccessDetails_Result> proc_verifyAccessDetails(string aPIUsername, string aPIKey, string accessToken)
        {
            var aPIUsernameParameter = aPIUsername != null ?
                new ObjectParameter("APIUsername", aPIUsername) :
                new ObjectParameter("APIUsername", typeof(string));
    
            var aPIKeyParameter = aPIKey != null ?
                new ObjectParameter("APIKey", aPIKey) :
                new ObjectParameter("APIKey", typeof(string));
    
            var accessTokenParameter = accessToken != null ?
                new ObjectParameter("AccessToken", accessToken) :
                new ObjectParameter("AccessToken", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_verifyAccessDetails_Result>("proc_verifyAccessDetails", aPIUsernameParameter, aPIKeyParameter, accessTokenParameter);
        }
    }
}
